import type { Metadata } from "next";
import "./globals.css";
import { Fira_Code } from 'next/font/google'

const firaCode = Fira_Code({
  variable: '--font-firaCode',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700']
})


export const metadata: Metadata = {
  title: "Faisal03_develop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={firaCode.className}>
      <body
        className={`${firaCode.variable} ${firaCode.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
